//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shohinkanri.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHOHIN
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> PRICE { get; set; }
    
        public virtual STOCK STOCK { get; set; }
    }
}
