//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shohinkanri.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCK
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> PRICE { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public Nullable<int> TOTAL_AMOUNT { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
    
        public virtual SHOHIN SHOHIN { get; set; }
    }
}
